zone/frontend

packages/eslint-config-react/package.json
packages/eslint-config-vue/package.json

Fixes #22 by adding eslint as a dev dependency

---

packages/eslint-config-react/__snapshots__/index.test.js.snap
packages/eslint-config-vue/__snapshots__/index.test.js.snap
packages/eslint-config-zone/__snapshots__/index.test.js.snap
packages/eslint-config-zone/config.json

Adding 'padding-line-between-statements' rule to base eslint config

---

packages/browserslist-config/__snapshots__/index.test.js.snap
yarn.lock

Other
No
Yes
Bumping packages to latest versions

Updating packages

---

package.json
yarn.lock

Manually creating PR after build timeout. All tests have passed so merging this as expected.

Greenkeeper/lerna 3.8.4

---

packages/browserslist-config/.npmignore
packages/eslint-config-react/.npmignore
packages/eslint-config-vue/.npmignore
packages/eslint-config-zone/.npmignore
packages/jarvis/.npmignore
packages/stylelint-config-zone/.npmignore

Other
No
Yes
Has reduced the following package sizes
Package | Reduced by
------- | ----------
browserslist-config | 50%
eslint-config-react | 85%
eslint-config-vue | 85%
eslint-config-zone | 83%

Fixes #37 adding ignore files to packages

---

packages/eslint-config-react/__snapshots__/index.test.js.snap
packages/eslint-config-react/config.json
packages/eslint-config-react/package.json
yarn.lock

Feature
No
Yes
This add the react hooks eslint rules to the Zone react rules package. Violation of hooks rules will result in a lint error.

Fixes #13 - Adds the eslint React hooks package and ruleset

---

greenkeeper.json

Fixes #51 - Adding greenkeeper groups

---

package.json
packages/eslint-config-react/package.json
packages/eslint-config-vue/package.json
packages/eslint-config-zone/package.json
packages/zoneify/package.json
yarn.lock

Greenkeeper/configs/eslint 5.15.0

---

package.json
yarn.lock

Update to jest for Node 11

---

packages/eslint-config-react/package.json
yarn.lock

Other - Updating eslint React hooks rules
No
Yes

Greenkeeper/configs/eslint plugin react hooks 1.5.1

---

packages/eslint-config-react/package.json

Greenkeeper/configs/eslint plugin react 7.13.0

---

packages/eslint-config-vue/package.json
yarn.lock

Updates to latest Vue eslint plugin
No
Yes

Updating to latest vue eslint plugin

---

packages/stylelint-config-zone/package.json
yarn.lock

Updates to latest stylelint
No
Yes

Updating to latest stylelint

---

packages/zoneify/package.json
yarn.lock

Updates command dependency for zoneify package
No
Yes

Updating commander

---

packages/stylelint-config-zone/__snapshots__/index.test.js.snap
packages/stylelint-config-zone/index.js
packages/stylelint-config-zone/index.test.js

bugfix/chore - Adding better test + fix for stylelint/prettier
No
Yes

Adding stylelint config test + fixing stylelint-printer integration

---

package.json
yarn.lock

Updating eslint + lerna

---

package.json
yarn.lock

Updating Jest to v25

---

README.md
packages/eslint-config-typescript/README.md
packages/eslint-config-typescript/__snapshots__/index.test.js.snap
packages/eslint-config-typescript/index.js
packages/eslint-config-typescript/index.test.js
packages/eslint-config-typescript/package.json
yarn.lock

Feature
No
Yes
This adds an experimental config for TypeScript.
While this won't require a major bump, I think we should probably do some other work on how we combine the TS config with React/Vue configs and the base. 
@jamieinthezone It might be worth using this in 'the project' you are currently looking at. Would be good to get some real-world input.

[Feature] Adding initial TypeScript Eslint config

---

yarn.lock

Chore - Updates patch and minor dependencies
No
Yes

Chore: Updating minor/patch dependencies

---

.github/CONTRIBUTING.md
README.md

Chore: Update Travis URLs

---

packages/eslint-config-react/__snapshots__/index.test.js.snap
packages/eslint-config-typescript/__snapshots__/index.test.js.snap
packages/eslint-config-vue/__snapshots__/index.test.js.snap
packages/eslint-config-zone/__snapshots__/index.test.js.snap
packages/eslint-config-zone/package.json
yarn.lock

Minor version bumps for eslint base and eslint prettier config

---

packages/browserslist-config/index.js

Updating browser list config to match latest browser matrix

---

packages/eslint-config-react/__snapshots__/index.test.js.snap
packages/eslint-config-react/index.js
packages/eslint-config-vue/__snapshots__/index.test.js.snap
packages/eslint-config-vue/index.js

Bugfix
Yes
Yes
This turns off rules that clash with prettier.

Fixes #145 - Using Prettier configurations for React and Vue
